import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";

import { Nunito } from 'next/font/google'
import PizzaModal from "@/components/modals/choose-pizza-modal";
import AppProvider from "@/providers/app-provider";
import CartDrawer from "@/components/cart/cart-drawer";
import AuthDrawer from "@/components/auth/auth-drawer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ['cyrillic'],
  weight: '600',
  variable: '--font-nunito'
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${nunito.variable}`}>
        <AppProvider>
          <AuthDrawer/>
          <CartDrawer/>
          <PizzaModal/>     

          <Header/>
          <Toaster />
          
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
